import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';

// A user's private podcast feed of their weekly audio briefings. Authenticated by
// the opaque ?token in the URL (a read-only, revocable feed credential) — this is
// /api/*, exempt from the auth middleware, so the token IS the auth.

function xmlEscape(s: string): string {
    return s
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;')
        .replace(/'/g, '&apos;');
}

export async function GET(request: NextRequest) {
    const token = request.nextUrl.searchParams.get('token');
    if (!token) return new NextResponse('Missing token', { status: 400 });

    const user = await prisma.user.findUnique({
        where: { apiToken: token },
        select: { id: true, name: true },
    });
    if (!user) return new NextResponse('Invalid token', { status: 404 });

    const briefings = await prisma.briefing.findMany({
        where: { userId: user.id },
        orderBy: { createdAt: 'desc' },
        take: 52,
        select: { id: true, audioUrl: true, durationSec: true, createdAt: true },
    });

    const base = (process.env.NEXTAUTH_URL || 'https://www.podcatch.app').replace(/\/$/, '');
    const feedTitle = `Podcatch Briefing${user.name ? ` for ${user.name}` : ''}`;

    const items = briefings.map(b => {
        const date = new Date(b.createdAt);
        const title = `Weekly Briefing — ${date.toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}`;
        return `    <item>
      <title>${xmlEscape(title)}</title>
      <guid isPermaLink="false">${b.id}</guid>
      <pubDate>${date.toUTCString()}</pubDate>
      <enclosure url="${xmlEscape(b.audioUrl)}" type="audio/mpeg" length="0" />
      <itunes:duration>${b.durationSec}</itunes:duration>
    </item>`;
    }).join('\n');

    const xml = `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd">
  <channel>
    <title>${xmlEscape(feedTitle)}</title>
    <link>${base}/briefings</link>
    <description>Your personal weekly audio recap, generated by Podcatch.</description>
    <language>en-us</language>
    <itunes:author>Podcatch</itunes:author>
    <itunes:explicit>false</itunes:explicit>
${items}
  </channel>
</rss>`;

    return new NextResponse(xml, {
        status: 200,
        headers: {
            'Content-Type': 'application/rss+xml; charset=utf-8',
            'Cache-Control': 'public, max-age=600',
        },
    });
}
