import Anthropic, { toFile } from '@anthropic-ai/sdk';

type SyncToClaudeParams = {
    apiKey: string;
    projectId: string;
    episodeTitle: string;
    feedTitle: string;
    publishedAt: Date;
    summary: string;
    keyTakeaways: string[];
    links: string[];
    transcript: string;
};

/**
 * Persists a podcast episode's transcript and insights into the user's Anthropic
 * workspace via the Files API.
 *
 * Note: the public Anthropic API has no endpoint for adding a document to a
 * Claude *Project* knowledge base — "Projects" is a claude.ai product feature,
 * not an API surface. So this uploads the document through the Files API (usable
 * from the Anthropic Console and as a `document` block in the Messages API)
 * rather than pretending to write into a Project. Previously this function sent
 * the transcript as a throwaway chat message and discarded the reply, burning
 * the user's tokens while syncing nothing.
 */
export async function syncEpisodeToClaude(params: SyncToClaudeParams) {
    const {
        apiKey,
        episodeTitle,
        feedTitle,
        publishedAt,
        summary,
        keyTakeaways,
        links,
        transcript,
    } = params;

    try {
        const claude = new Anthropic({ apiKey });

        // Format the content as a self-contained Markdown document.
        const documentContent = `# ${episodeTitle}

**Podcast**: ${feedTitle}
**Published**: ${publishedAt.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}

## Summary

${summary}

## Key Takeaways

${keyTakeaways.map((takeaway, i) => `${i + 1}. ${takeaway}`).join('\n')}

${links.length > 0 ? `\n## Links Mentioned\n\n${links.map((link) => `- ${link}`).join('\n')}` : ''}

## Full Transcript

${transcript}

---

*Auto-generated by Podcatch - podcast intelligence automation*
`;

        const safeName =
            episodeTitle.replace(/[^a-z0-9]+/gi, '-').replace(/^-+|-+$/g, '').slice(0, 80) ||
            'episode';

        const file = await claude.beta.files.upload({
            file: await toFile(Buffer.from(documentContent, 'utf-8'), `${safeName}.md`, {
                type: 'text/markdown',
            }),
            betas: ['files-api-2025-04-14'],
        });

        console.log(`✅ Uploaded "${episodeTitle}" to Claude Files (${file.id})`);

        return {
            success: true,
            fileId: file.id,
            message: 'Transcript and insights uploaded to your Claude workspace.',
        };
    } catch (error) {
        console.error('Error uploading episode to Claude:', error);
        return {
            success: false,
            error: error instanceof Error ? error.message : 'Failed to upload to Claude',
        };
    }
}
